# Generated by Django 2.1.1 on 2019-02-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('denomination', models.CharField(max_length=128)),
                ('services', models.IntegerField()),
                ('serviceTimes', models.CharField(max_length=128)),
                ('website', models.CharField(max_length=128)),
                ('podcast', models.CharField(max_length=128)),
                ('pastor', models.CharField(max_length=128)),
                ('noCampuses', models.IntegerField()),
                ('size', models.IntegerField()),
                ('ageRange13_24', models.IntegerField()),
                ('ageRange25_35', models.IntegerField()),
                ('ageRange35_55', models.IntegerField()),
                ('ageRange55', models.IntegerField()),
                ('perFamily', models.IntegerField()),
                ('startDate', models.DateField()),
                ('sundaySchool', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('smallGroups', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('preachingStyle', models.CharField(choices=[('T', 'Topical'), ('V', 'Verse-by-verse'), ('N', 'Narrative'), ('O', 'Other'), ('M', 'Mix')], max_length=1)),
                ('leadPic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='model_churchpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churchpic', to='churches.model_church')),
            ],
        ),
    ]
