# Generated by Django 2.1.1 on 2019-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_auto_20190205_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_church',
            name='phoneNumber',
            field=models.CharField(default='(888) 123-4567', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_church',
            name='leadPic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
