# Generated by Django 2.1.7 on 2019-04-05 15:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_auto_20190305_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_church',
            name='location',
            field=tinymce.models.HTMLField(max_length=128),
        ),
    ]
